// @generated by rocci-ungram. Do not edit.

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Document {
    pub items: Vec<Item>,
    pub span: Span,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Item {
    Block(Block),
    Leaf { span: Span },
}

impl Item {
    pub fn span(&self) -> Span {
        match self {
            Self::Block(item) => item.span,
            Self::Leaf { span } => *span,
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Block {
    pub name: Ident,
    pub child: Option<Node>,
    pub span: Span,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Ident {
    pub name: String,
    pub span: Span,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Node {
    pub inner: Box<Node>,
    pub span: Span,
}
