use std::path::Path;

use crate::dialect::Error;
use crate::inspect::format_appendix_table;
use crate::paths::{
    ROCCI_TOML, ROCCI_TREE_APPENDIX, ROCCI_UNGRAM, ROCDOWN_MARKDOWN_TOML, ROCDOWN_MARKDOWN_UNGRAM,
    ROCDOWN_TOML, ROCDOWN_TREE_APPENDIX, ROCDOWN_UNGRAM,
};

pub fn generate_appendices(root: &Path) -> Result<Vec<(std::path::PathBuf, String)>, Error> {
    Ok(vec![
        (
            root.join(ROCCI_TREE_APPENDIX),
            rocci_page(
                &std::fs::read_to_string(root.join(ROCCI_UNGRAM))?,
                &std::fs::read_to_string(root.join(ROCCI_TOML))?,
            )?,
        ),
        (
            root.join(ROCDOWN_TREE_APPENDIX),
            rocdown_page(
                &std::fs::read_to_string(root.join(ROCDOWN_UNGRAM))?,
                &std::fs::read_to_string(root.join(ROCDOWN_TOML))?,
                &std::fs::read_to_string(root.join(ROCDOWN_MARKDOWN_UNGRAM))?,
                &std::fs::read_to_string(root.join(ROCDOWN_MARKDOWN_TOML))?,
            )?,
        ),
    ])
}

fn rocci_page(ungram: &str, sidecar: &str) -> Result<String, Error> {
    Ok(page(
        "Rocci tree appendix",
        &["/reference/rocci-tree/", "/docs/reference/rocci-tree/"],
        "Owned AST productions, inspect tags, and sidecar classification for .rocci files.",
        "This page is generated from `crates/rocci-template/Rocci.AST.ungram`. It is a tree spec for owned AST nodes, not the language of strings; scanners stay hand-written. Inspect tags live in `Rocci.AST.toml`. Do not edit this file by hand; run `cargo run -q -p rocci-ungram -- generate`.",
        &[("Productions", &format_appendix_table(ungram, sidecar)?)],
    ))
}

fn rocdown_page(
    document_ungram: &str,
    document_sidecar: &str,
    markdown_ungram: &str,
    markdown_sidecar: &str,
) -> Result<String, Error> {
    Ok(page(
        "Rocdown tree appendix",
        &["/reference/rocdown-tree/", "/docs/reference/rocdown-tree/"],
        "Owned AST productions, inspect tags, and sidecar classification for .rocdown files.",
        "This page is generated from `crates/rocci-rocdown/Rocdown.AST.ungram` and `crates/rocci-rocdown/Rocdown.Markdown.ungram`. It is a tree spec for owned AST nodes, not the language of strings; scanners stay hand-written. Inspect tags live in the sibling TOML sidecars. Do not edit this file by hand; run `cargo run -q -p rocci-ungram -- generate`.",
        &[
            (
                "Document tree",
                &format_appendix_table(document_ungram, document_sidecar)?,
            ),
            (
                "Markdown projection",
                &format_appendix_table(markdown_ungram, markdown_sidecar)?,
            ),
        ],
    ))
}

fn page(
    title: &str,
    aliases: &[&str],
    description: &str,
    lead: &str,
    sections: &[(&str, &str)],
) -> String {
    let mut out = String::new();
    out.push_str("@page {\n");
    out.push_str("    layout: \"docs\",\n");
    let quoted: Vec<String> = aliases.iter().map(|alias| format!("\"{alias}\"")).collect();
    out.push_str(&format!("    aliases: [{}],\n\n", quoted.join(", ")));
    out.push_str("    meta: {\n");
    out.push_str(&format!("        title: \"{title}\",\n"));
    out.push_str(&format!("        description: \"{description}\",\n"));
    out.push_str("    },\n");
    out.push_str("}\n\n");
    out.push_str(&format!("# {title}\n\n"));
    out.push_str(lead);
    out.push_str("\n");
    for (heading, table) in sections {
        out.push_str("\n");
        out.push_str(&format!("## {heading}\n\n"));
        out.push_str(table);
    }
    out
}
