use crate::dialect::{Ir, Item};
use crate::sidecar::Sidecar;

pub fn emit_node_kind(ir: &Ir, sidecar: &Sidecar) -> String {
    let names: Vec<&str> = ir
        .items
        .iter()
        .map(|item| match item {
            Item::Struct { name, .. } | Item::Enum { name, .. } => name.as_str(),
        })
        .collect();
    let mut out = String::from("// @generated by rocci-ungram. Do not edit.\n\n");
    out.push_str("#![allow(dead_code)]\n\n");
    out.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]\n");
    out.push_str("pub(crate) enum NodeKind {\n");
    for name in &names {
        out.push_str("    ");
        out.push_str(name);
        out.push_str(",\n");
    }
    out.push_str("}\n\nimpl NodeKind {\n    pub(crate) const ALL: &[NodeKind] = &[\n");
    for name in &names {
        out.push_str("        NodeKind::");
        out.push_str(name);
        out.push_str(",\n");
    }
    out.push_str("    ];\n\n    pub(crate) fn highlight_omitted(self) -> bool {\n");
    let omitted: Vec<&str> = names
        .iter()
        .copied()
        .filter(|name| sidecar.highlight.omit.contains_key(*name))
        .collect();
    if omitted.is_empty() {
        out.push_str("        false\n");
    } else {
        out.push_str("        matches!(\n            self,\n");
        let arms: Vec<String> = omitted
            .iter()
            .map(|name| format!("NodeKind::{name}"))
            .collect();
        let one_line = arms.join(" | ");
        if 12 + one_line.len() <= 100 {
            out.push_str("            ");
            out.push_str(&one_line);
            out.push('\n');
        } else {
            out.push_str("            ");
            out.push_str(&arms[0]);
            for arm in &arms[1..] {
                out.push_str("\n                | ");
                out.push_str(arm);
            }
            out.push('\n');
        }
        out.push_str("        )\n");
    }
    out.push_str("    }\n}\n");
    out
}
