use std::collections::BTreeSet;

use crate::dialect::{Field, Ir, Item, Ty, Variant};
use crate::sidecar::Sidecar;

pub fn emit_pprint(ir: &Ir, sidecar: &Sidecar) -> String {
    let writers = writer_types(ir, sidecar);
    let mut chunks = Vec::new();
    for item in &ir.items {
        let chunk = match item {
            Item::Enum { name, variants } if writers.contains(name) => {
                emit_enum_writer(sidecar, name, variants)
            }
            Item::Struct { name, fields } if writers.contains(name) => {
                emit_struct_writer(sidecar, name, fields, &writers)
            }
            _ => String::new(),
        };
        if !chunk.is_empty() {
            chunks.push(chunk);
        }
    }
    let mut out = String::from("// @generated by rocci-ungram. Do not edit.\n");
    for chunk in chunks {
        out.push('\n');
        out.push_str(&chunk);
        if !out.ends_with('\n') {
            out.push('\n');
        }
    }
    out
}

fn writer_types(ir: &Ir, sidecar: &Sidecar) -> BTreeSet<String> {
    let mut writers = BTreeSet::new();
    loop {
        let mut added = false;
        for item in &ir.items {
            match item {
                Item::Enum { name, .. } => {
                    if !sidecar.inspect.overlay.contains_key(name) && writers.insert(name.clone()) {
                        added = true;
                    }
                }
                Item::Struct { name, fields } => {
                    if sidecar.inspect.overlay.contains_key(name) {
                        continue;
                    }
                    let include = sidecar.inspect.tags.contains_key(name)
                        || fields.iter().any(|field| {
                            peel_named(&field.ty).is_some_and(|ty| writers.contains(ty))
                        });
                    if include && writers.insert(name.clone()) {
                        added = true;
                    }
                }
            }
        }
        if !added {
            break;
        }
    }
    writers
}

fn emit_enum_writer(sidecar: &Sidecar, name: &str, variants: &[Variant]) -> String {
    let fn_name = write_fn_name(name);
    let mut out = String::new();
    out.push_str(&format!(
        "fn {fn_name}(w: &mut Writer<'_>, src: &str, item: &{name}) {{\n    match item {{\n"
    ));
    for variant in variants {
        out.push_str("        ");
        out.push_str(&enum_arm(sidecar, name, variant));
        out.push('\n');
    }
    out.push_str("    }\n}\n");
    out
}

fn enum_arm(sidecar: &Sidecar, enum_name: &str, variant: &Variant) -> String {
    match variant {
        Variant::Unit { name } => {
            let call = overlay_call(sidecar, enum_name, name, None);
            format!("{enum_name}::{name} => {call},")
        }
        Variant::Tuple { name, ty } => {
            let payload = named_type(ty);
            let call = overlay_call(sidecar, enum_name, name, payload);
            format!("{enum_name}::{name}(item) => {call},")
        }
        Variant::Struct { name, fields } => {
            let names: Vec<&str> = fields.iter().map(|field| field.name.as_str()).collect();
            let pattern = names.join(", ");
            let production = production_for_variant(sidecar, enum_name, name);
            let func = overlay_func(sidecar, enum_name, name, Some(&production));
            if names.len() == 1 {
                format!("{enum_name}::{name} {{ {pattern} }} => {func}(w, src, {pattern}),")
            } else {
                let binds = names.join(", ");
                format!("{enum_name}::{name} {{ {binds} }} => {func}(w, src, {pattern}),")
            }
        }
    }
}

fn overlay_call(
    sidecar: &Sidecar,
    enum_name: &str,
    variant_name: &str,
    payload: Option<&str>,
) -> String {
    let production = production_for_variant(sidecar, enum_name, variant_name);
    let func = overlay_func(
        sidecar,
        enum_name,
        variant_name,
        payload.or(Some(&production)),
    );
    if payload.is_none() {
        format!("{func}(w, src)")
    } else {
        format!("{func}(w, src, item)")
    }
}

fn overlay_func(
    sidecar: &Sidecar,
    enum_name: &str,
    variant_name: &str,
    payload: Option<&str>,
) -> String {
    let production = production_for_variant(sidecar, enum_name, variant_name);
    sidecar
        .inspect
        .overlay
        .get(&format!("{enum_name}.{variant_name}"))
        .or_else(|| sidecar.inspect.overlay.get(&production))
        .or_else(|| payload.and_then(|ty| sidecar.inspect.overlay.get(ty)))
        .cloned()
        .unwrap_or_else(|| {
            payload
                .map(write_fn_name)
                .unwrap_or_else(|| write_fn_name(&production))
        })
}

fn production_for_variant(sidecar: &Sidecar, enum_name: &str, variant_name: &str) -> String {
    if let Some(map) = sidecar.variants.get(enum_name) {
        for (production, variant) in map {
            if variant == variant_name {
                return production.clone();
            }
        }
    }
    variant_name.to_string()
}

fn emit_struct_writer(
    sidecar: &Sidecar,
    name: &str,
    fields: &[Field],
    writers: &BTreeSet<String>,
) -> String {
    let walks = field_walks(fields, writers);
    let tagged = sidecar.inspect.tags.get(name).cloned();
    let fn_name = write_fn_name(name);
    let mut out = String::new();
    out.push_str(&format!(
        "fn {fn_name}(w: &mut Writer<'_>, src: &str, node: &{name}) {{\n"
    ));
    if let Some(tag) = tagged {
        if walks.is_empty() {
            out.push_str(&format!("    w.leaf(\"{tag}\", &[]);\n"));
        } else {
            out.push_str(&format!("    w.open(\"{tag}\", &[]);\n"));
            for walk in &walks {
                out.push_str(walk);
            }
            out.push_str("    w.close();\n");
        }
    } else {
        for walk in &walks {
            out.push_str(walk);
        }
    }
    out.push_str("}\n");
    out
}

fn field_walks(fields: &[Field], writers: &BTreeSet<String>) -> Vec<String> {
    fields
        .iter()
        .filter_map(|field| field_walk(field, writers))
        .collect()
}

fn field_walk(field: &Field, writers: &BTreeSet<String>) -> Option<String> {
    let (loop_kind, ty_name) = peel_ty(&field.ty)?;
    if !writers.contains(ty_name) {
        return None;
    }
    let call = write_fn_name(ty_name);
    let access = format!("node.{}", field.name);
    Some(match loop_kind {
        LoopKind::Once => format!("    {call}(w, src, &{access});\n"),
        LoopKind::Vec => {
            format!("    for item in &{access} {{\n        {call}(w, src, item);\n    }}\n")
        }
        LoopKind::Option => {
            format!("    if let Some(item) = &{access} {{\n        {call}(w, src, item);\n    }}\n")
        }
        LoopKind::Box => format!("    {call}(w, src, {access}.as_ref());\n"),
    })
}

#[derive(Clone, Copy)]
enum LoopKind {
    Once,
    Vec,
    Option,
    Box,
}

fn peel_ty(ty: &Ty) -> Option<(LoopKind, &str)> {
    match ty {
        Ty::Named(name) => Some((LoopKind::Once, name.as_str())),
        Ty::Vec(inner) => match inner.as_ref() {
            Ty::Named(name) => Some((LoopKind::Vec, name.as_str())),
            _ => None,
        },
        Ty::Option(inner) => match inner.as_ref() {
            Ty::Named(name) => Some((LoopKind::Option, name.as_str())),
            _ => peel_ty(inner).map(|(_, name)| (LoopKind::Option, name)),
        },
        Ty::Box(inner) => match inner.as_ref() {
            Ty::Named(name) => Some((LoopKind::Box, name.as_str())),
            _ => None,
        },
        Ty::Tuple(_) | Ty::Raw(_) => None,
    }
}

fn peel_named(ty: &Ty) -> Option<&str> {
    peel_ty(ty).map(|(_, name)| name)
}

fn named_type(ty: &Ty) -> Option<&str> {
    match ty {
        Ty::Named(name) => Some(name.as_str()),
        Ty::Box(inner) => named_type(inner),
        _ => None,
    }
}

fn write_fn_name(type_name: &str) -> String {
    let mut out = String::from("write_");
    out.push_str(&pascal_to_snake(type_name));
    out
}

fn pascal_to_snake(name: &str) -> String {
    let mut out = String::new();
    for (i, ch) in name.chars().enumerate() {
        if ch.is_uppercase() {
            if i > 0 {
                out.push('_');
            }
            out.push(ch.to_ascii_lowercase());
        } else {
            out.push(ch);
        }
    }
    out
}
