use crate::dialect::{Ir, Item, Variant};

pub fn emit(ir: &Ir) -> String {
    let mut out = String::from("// @generated by rocci-ungram. Do not edit.\n\n");
    for path in &ir.uses {
        emit_use(&mut out, path);
    }
    if !ir.uses.is_empty() {
        out.push('\n');
    }
    for (index, item) in ir.items.iter().enumerate() {
        if index > 0 {
            out.push('\n');
        }
        match item {
            Item::Struct { name, fields } => emit_struct(&mut out, name, fields),
            Item::Enum { name, variants } => {
                emit_enum(&mut out, name, variants);
                if let Some(body) = span_impl(name, variants, &ir.span_method) {
                    out.push('\n');
                    out.push_str(&body);
                }
            }
        }
    }
    if !out.ends_with('\n') {
        out.push('\n');
    }
    out
}

fn emit_use(out: &mut String, path: &str) {
    if let Some((head, rest)) = path.split_once("::{") {
        let names: Vec<&str> = rest
            .trim()
            .trim_end_matches('}')
            .split(',')
            .map(str::trim)
            .filter(|name| !name.is_empty())
            .collect();
        let single = format!("use {path};");
        if single.len() > 100 && !names.is_empty() {
            out.push_str("use ");
            out.push_str(head);
            out.push_str("::{\n");
            for name in names {
                out.push_str("    ");
                out.push_str(name);
                out.push_str(",\n");
            }
            out.push_str("};\n");
            return;
        }
    }
    out.push_str("use ");
    out.push_str(path);
    out.push_str(";\n");
}

fn emit_struct(out: &mut String, name: &str, fields: &[crate::dialect::Field]) {
    out.push_str("#[derive(Clone, Debug, PartialEq, Eq)]\n");
    out.push_str("pub struct ");
    out.push_str(name);
    out.push_str(" {\n");
    for field in fields {
        out.push_str("    pub ");
        out.push_str(&field.name);
        out.push_str(": ");
        out.push_str(&field.ty.to_string());
        out.push_str(",\n");
    }
    out.push_str("}\n");
}

fn emit_enum(out: &mut String, name: &str, variants: &[Variant]) {
    out.push_str("#[derive(Clone, Debug, PartialEq, Eq)]\n");
    out.push_str("pub enum ");
    out.push_str(name);
    out.push_str(" {\n");
    for variant in variants {
        match variant {
            Variant::Unit { name } => {
                out.push_str("    ");
                out.push_str(name);
                out.push_str(",\n");
            }
            Variant::Tuple { name, ty } => {
                out.push_str("    ");
                out.push_str(name);
                out.push('(');
                out.push_str(&ty.to_string());
                out.push_str("),\n");
            }
            Variant::Struct { name, fields } => {
                out.push_str("    ");
                out.push_str(name);
                out.push_str(" { ");
                for (i, field) in fields.iter().enumerate() {
                    if i > 0 {
                        out.push_str(", ");
                    }
                    out.push_str(&field.name);
                    out.push_str(": ");
                    out.push_str(&field.ty.to_string());
                }
                out.push_str(" },\n");
            }
        }
    }
    out.push_str("}\n");
}

fn span_impl(
    name: &str,
    variants: &[Variant],
    span_method: &std::collections::BTreeSet<String>,
) -> Option<String> {
    let mut arms = Vec::new();
    for variant in variants {
        arms.push(span_arm(variant, span_method)?);
    }
    let mut out = String::new();
    out.push_str("impl ");
    out.push_str(name);
    out.push_str(" {\n    pub fn span(&self) -> Span {\n        match self {\n");
    for arm in arms {
        out.push_str("            ");
        out.push_str(&arm);
        out.push('\n');
    }
    out.push_str("        }\n    }\n}\n");
    Some(out)
}

fn span_arm(variant: &Variant, span_method: &std::collections::BTreeSet<String>) -> Option<String> {
    match variant {
        Variant::Unit { .. } => None,
        Variant::Tuple { name, ty } => {
            let expr = tuple_span_expr(ty, span_method)?;
            Some(format!("Self::{name}(item) => {expr},"))
        }
        Variant::Struct { name, fields } => {
            if fields.iter().any(|field| field.name == "span") {
                let rest = if fields.len() > 1 { ", .." } else { "" };
                Some(format!("Self::{name} {{ span{rest} }} => *span,"))
            } else {
                None
            }
        }
    }
}

fn tuple_span_expr(
    ty: &crate::dialect::Ty,
    span_method: &std::collections::BTreeSet<String>,
) -> Option<String> {
    match ty {
        crate::dialect::Ty::Named(name) if span_method.contains(name) => Some("item.span()".into()),
        crate::dialect::Ty::Named(_) => Some("item.span".into()),
        crate::dialect::Ty::Box(inner) => tuple_span_expr(inner, span_method),
        _ => None,
    }
}
