[package]
name = "rocci-highlight"
version.workspace = true
edition.workspace = true
license-file.workspace = true
description = "Shared lexical highlighting library for Roc, HTML, CSS, Rocci, and Rocdown"

[lib]
name = "rocci_highlight"
path = "src/lib.rs"

[dependencies]
rocci-template = { workspace = true }
serde = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tree-sitter = "0.27.0"

[build-dependencies]
cc = "1.0"
