[package]
name = "counter"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true

[features]
default = ["desktop"]
desktop = ["rocci/desktop"]

[dependencies]
anyhow = { workspace = true }
async-stream = { workspace = true }
askama = { workspace = true }
axum = { workspace = true }
datastar = { workspace = true }
futures-util = { workspace = true }
http = { workspace = true }
rocci = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
http-body-util = { workspace = true }
tower = { workspace = true }

[build-dependencies]
rocci-core = { workspace = true }
