// @generated by rocci-ungram. Do not edit.

use rocci_template::Span;

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum MdNode {
    Heading {
        level: u8,
        id: String,
        children: Vec<MdNode>,
        span: Span,
    },
    Paragraph {
        children: Vec<MdNode>,
        span: Span,
    },
    BlockQuote {
        children: Vec<MdNode>,
        span: Span,
    },
    List {
        ordered: bool,
        start: u64,
        children: Vec<MdNode>,
        span: Span,
    },
    Item {
        children: Vec<MdNode>,
        span: Span,
    },
    TaskItem {
        checked: bool,
        children: Vec<MdNode>,
        span: Span,
    },
    CodeBlock {
        info: String,
        literal: String,
        span: Span,
    },
    ThematicBreak {
        span: Span,
    },
    Table {
        children: Vec<MdNode>,
        span: Span,
    },
    TableRow {
        header: bool,
        children: Vec<MdNode>,
        span: Span,
    },
    TableCell {
        children: Vec<MdNode>,
        span: Span,
    },
    Text {
        value: String,
        span: Span,
    },
    Interpolation {
        expr: Span,
        span: Span,
    },
    SoftBreak {
        span: Span,
    },
    LineBreak {
        span: Span,
    },
    Code {
        value: String,
        span: Span,
    },
    Emph {
        children: Vec<MdNode>,
        span: Span,
    },
    Strong {
        children: Vec<MdNode>,
        span: Span,
    },
    Strikethrough {
        children: Vec<MdNode>,
        span: Span,
    },
    FootnoteDefinition {
        name: String,
        total_references: u32,
        children: Vec<MdNode>,
        span: Span,
    },
    FootnoteReference {
        name: String,
        reference_number: u32,
        index: u32,
        span: Span,
    },
    Link {
        url: String,
        title: String,
        children: Vec<MdNode>,
        span: Span,
    },
    Image {
        url: String,
        title: String,
        alt: String,
        span: Span,
    },
    RawHtml {
        html: String,
        span: Span,
    },
}

impl MdNode {
    pub fn span(&self) -> Span {
        match self {
            Self::Heading { span, .. } => *span,
            Self::Paragraph { span, .. } => *span,
            Self::BlockQuote { span, .. } => *span,
            Self::List { span, .. } => *span,
            Self::Item { span, .. } => *span,
            Self::TaskItem { span, .. } => *span,
            Self::CodeBlock { span, .. } => *span,
            Self::ThematicBreak { span } => *span,
            Self::Table { span, .. } => *span,
            Self::TableRow { span, .. } => *span,
            Self::TableCell { span, .. } => *span,
            Self::Text { span, .. } => *span,
            Self::Interpolation { span, .. } => *span,
            Self::SoftBreak { span } => *span,
            Self::LineBreak { span } => *span,
            Self::Code { span, .. } => *span,
            Self::Emph { span, .. } => *span,
            Self::Strong { span, .. } => *span,
            Self::Strikethrough { span, .. } => *span,
            Self::FootnoteDefinition { span, .. } => *span,
            Self::FootnoteReference { span, .. } => *span,
            Self::Link { span, .. } => *span,
            Self::Image { span, .. } => *span,
            Self::RawHtml { span, .. } => *span,
        }
    }
}
