// @generated by rocci-ungram. Do not edit.

#![allow(dead_code)]

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub(crate) enum NodeKind {
    Document,
    Item,
    PageDecl,
    RocDecl,
    RenderDecl,
    UseDecl,
    BlockCall,
    BracketRecord,
    BlockContent,
    ParamField,
    ParamValue,
    BracketList,
    LineContent,
    BraceSection,
    EndSection,
    EndMarker,
}

impl NodeKind {
    pub(crate) const ALL: &[NodeKind] = &[
        NodeKind::Document,
        NodeKind::Item,
        NodeKind::PageDecl,
        NodeKind::RocDecl,
        NodeKind::RenderDecl,
        NodeKind::UseDecl,
        NodeKind::BlockCall,
        NodeKind::BracketRecord,
        NodeKind::BlockContent,
        NodeKind::ParamField,
        NodeKind::ParamValue,
        NodeKind::BracketList,
        NodeKind::LineContent,
        NodeKind::BraceSection,
        NodeKind::EndSection,
        NodeKind::EndMarker,
    ];

    pub(crate) fn highlight_omitted(self) -> bool {
        match self {
            NodeKind::BracketRecord => true,
            NodeKind::ParamField => true,
            NodeKind::ParamValue => true,
            NodeKind::BracketList => true,
            NodeKind::LineContent => true,
            NodeKind::BraceSection => true,
            NodeKind::EndSection => true,
            _ => false,
        }
    }
}
