// @generated by rocci-ungram. Do not edit.

fn write_document(w: &mut Writer<'_>, src: &str, node: &Document) {
    w.open("rocdown", &[]);
    for item in &node.items {
        write_item(w, src, item);
    }
    w.close();
}

fn write_item(w: &mut Writer<'_>, src: &str, item: &Item) {
    match item {
        Item::Markdown(item) => write_md(w, src, item),
        Item::Page(item) => write_page(w, src, item),
        Item::Roc(item) => write_roc_decl(w, src, item),
        Item::Render(item) => write_render(w, src, item),
        Item::Component(item) => write_component_leaf(w, src, item),
        Item::Fixture(item) => write_fixture_leaf(w, src, item),
        Item::Css(item) => write_css_leaf(w, src, item),
        Item::Context(item) => write_context_leaf(w, src, item),
        Item::Init(item) => write_init_leaf(w, src, item),
        Item::Live(item) => write_live_leaf(w, src, item),
        Item::View(item) => write_view_leaf(w, src, item),
        Item::Patch(item) => write_patch_leaf(w, src, item),
        Item::Command(item) => write_command_leaf(w, src, item),
        Item::Use(item) => write_use(w, src, item),
        Item::Template(item) => write_template_island(w, src, item),
        Item::Block(item) => write_block(w, src, item),
    }
}
