// @generated by rocci-ungram. Do not edit.

#![allow(dead_code)]

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub(crate) enum NodeKind {
    Document,
    ModuleItem,
    ComponentDecl,
    FixtureDecl,
    TestDecl,
    CssDecl,
    ContextDecl,
    InitDecl,
    RouteDecl,
    LeadingComments,
    Ident,
    TemplateBlock,
    ComponentPath,
    ViewDecl,
    FragmentDecl,
    CommandDecl,
    LiveDecl,
    TemplateItem,
    Element,
    ComponentCall,
    Fragment,
    TextNode,
    Interpolation,
    IfDirective,
    ForDirective,
    MatchDirective,
    LetDirective,
    Attr,
    AttrValue,
    MatchArm,
}

impl NodeKind {
    pub(crate) const ALL: &[NodeKind] = &[
        NodeKind::Document,
        NodeKind::ModuleItem,
        NodeKind::ComponentDecl,
        NodeKind::FixtureDecl,
        NodeKind::TestDecl,
        NodeKind::CssDecl,
        NodeKind::ContextDecl,
        NodeKind::InitDecl,
        NodeKind::RouteDecl,
        NodeKind::LeadingComments,
        NodeKind::Ident,
        NodeKind::TemplateBlock,
        NodeKind::ComponentPath,
        NodeKind::ViewDecl,
        NodeKind::FragmentDecl,
        NodeKind::CommandDecl,
        NodeKind::LiveDecl,
        NodeKind::TemplateItem,
        NodeKind::Element,
        NodeKind::ComponentCall,
        NodeKind::Fragment,
        NodeKind::TextNode,
        NodeKind::Interpolation,
        NodeKind::IfDirective,
        NodeKind::ForDirective,
        NodeKind::MatchDirective,
        NodeKind::LetDirective,
        NodeKind::Attr,
        NodeKind::AttrValue,
        NodeKind::MatchArm,
    ];

    pub(crate) fn highlight_omitted(self) -> bool {
        matches!(
            self,
            NodeKind::LeadingComments
                | NodeKind::Ident
                | NodeKind::TextNode
                | NodeKind::Interpolation
        )
    }
}
