// @generated by rocci-ungram. Do not edit.

fn write_document(w: &mut Writer<'_>, src: &str, node: &Document) {
    w.open("module", &[]);
    for item in &node.items {
        write_module_item(w, src, item);
    }
    w.close();
}

fn write_module_item(w: &mut Writer<'_>, src: &str, item: &ModuleItem) {
    match item {
        ModuleItem::Roc { span } => write_roc_region(w, src, span),
        ModuleItem::Component(item) => write_component(w, src, item),
        ModuleItem::Fixture(item) => write_fixture(w, src, item),
        ModuleItem::Test(item) => write_test(w, src, item),
        ModuleItem::Css(item) => write_css(w, src, item),
        ModuleItem::Context(item) => write_context(w, src, item),
        ModuleItem::Init(item) => write_init(w, src, item),
        ModuleItem::Route(item) => write_route_decl(w, src, item),
    }
}

fn write_route_decl(w: &mut Writer<'_>, src: &str, item: &RouteDecl) {
    match item {
        RouteDecl::View(item) => write_view(w, src, item),
        RouteDecl::Fragment(item) => write_fragment_decl(w, src, item),
        RouteDecl::Command(item) => write_command(w, src, item),
        RouteDecl::Live(item) => write_live(w, src, item),
    }
}

fn write_template_block(w: &mut Writer<'_>, src: &str, node: &TemplateBlock) {
    for item in &node.items {
        write_template_item(w, src, item);
    }
}

fn write_template_item(w: &mut Writer<'_>, src: &str, item: &TemplateItem) {
    match item {
        TemplateItem::Element(item) => write_element(w, src, item),
        TemplateItem::ComponentCall(item) => write_call(w, src, item),
        TemplateItem::Fragment(item) => write_fragment(w, src, item),
        TemplateItem::Text(item) => write_text(w, src, item),
        TemplateItem::Interpolation(item) => write_interp(w, src, item),
        TemplateItem::If(item) => write_if(w, src, item),
        TemplateItem::For(item) => write_for(w, src, item),
        TemplateItem::Match(item) => write_match(w, src, item),
        TemplateItem::Let(item) => write_let(w, src, item),
        TemplateItem::Css(item) => write_css(w, src, item),
    }
}
