[[plugin]]
id = "rocdown"
bin = "target/debug/rocdown"
argv = ["browser-adapter"]

[[plugin]]
id = "okf"
bin = "target/debug/rocci-okf"
argv = ["browser-adapter"]

[[plugin]]
id = "rocci"
bin = "target/debug/rocci"
argv = ["browser-adapter"]

[[project]]
id = "site"
path = "site"

[[project]]
id = "docs"
path = "docs"

[[project]]
id = "knowledge"
path = "knowledge"
