[package]
name = "rocs"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Rocs documentation generator built on Rocci templates and Rocdown"

[lib]
name = "rocs"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
rocci-template = { workspace = true }
rocci-rocdown = { workspace = true }
